- name: Install Docker and dependencies
  hosts: cloud_vm
  become: true
  tasks:
    - name: Update APT repositories
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add Docker’s official GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null
        chmod a+r /etc/apt/keyrings/docker.asc

    - name: Add Docker repository
      shell: |
        echo \
        "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update

    - name: Install Docker & Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Add user to Docker group
      shell: "usermod -aG docker ubuntu"

    - name: Restart Docker
      service:
        name: docker
        state: restarted
